// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qtxtfxnnrbedssfyzeyx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF0eHRmeG5ucmJlZHNzZnl6ZXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Njk0MTgsImV4cCI6MjA3MzQ0NTQxOH0.sEk5aUcXTA5V4g3SlLpH9QHcbClzMqnXtK99oK72aFc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});